accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
    CreateUser, UpdateUser, DeleteUser,
    LoginUser, LogoutUser, ProfileUser,
    ResetPasswordView
)

app_name = "accounts"

urlpatterns = [
    path('', ProfileUser.as_view(), name= 'home_user'),
    path('create/', CreateUser.as_view(), name='create_user'),
    path('login/', LoginUser.as_view(), name='login_user'),
    path('logout/', LogoutUser.as_view(), name='logout_user'),
    path('update/', UpdateUser.as_view(), name='update_user'),
    path('delete/', DeleteUser.as_view(), name='delete_user'),
    path('change-password/',auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html',
            success_url = reverse_lazy('accounts:home_user')
        ),
        name='change_password'
    ),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy("accounts:password_reset_complete")
            ),
            name='password_reset_confirm'
        ),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from django.conf import settings
from django.views.static import serve


from .views import HomeView, Handler404, Handler500

handler404 = Handler404.as_view()
handler500 = Handler500.as_view()

urlpatterns = [
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
        AbstractBaseUser, PermissionsMixin, UserManager
    )



class User(AbstractBaseUser, PermissionsMixin):

    
    username = models.CharField(
        'Usuário', max_length=30, null=False, blank=False,
        unique=True, error_messages={'unique' : "Usuário já cadastrado!"},
        help_text='Um nome curto para a sua identificação exclusiva no sistema.'
    )

    name = models.CharField(
        'Nome', max_length=255, null=False, blank=False
    )

    email = models.EmailField(
        'E-mail', blank=False, null=False, unique=True,
        error_messages = {'unique' : "E-mail já cadastrado!"},
        help_text = 'Para envio de notificações se caso necessário.'
    )

    is_staff = models.BooleanField(default = False)
    is_superuser = models.BooleanField(default = False)
    is_active = models.BooleanField(default = True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = 'usuário'
        verbose_name_plural = 'usuários'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


class CreationUserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username','name', 'email',)


class ChangeUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username','name', 'email',)

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
        CreateView, UpdateView, DeleteView, View
    )
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from .models import User
from .forms import CreationUserForm, ChangeUserForm


class ProfileUser(LoginRequiredMixin, View):


    template_name = 'accounts/login.html'

    def get(self, request):
        return render(request, 'accounts/profile.html')
        

class LoginUser(LoginView):


    template_name = 'accounts/login.html'

    def form_valid(self, form):
        user = form.get_user()
        messages.success(self.request, f'Bem vindo {user}')
        return super().form_valid(form)


class LogoutUser(LogoutView):
    
    
    template_name = 'base.html'

    def get_success_url_allowed_hosts(self):
        messages.info(self.request,'Até breve!')
        return super().get_success_url_allowed_hosts()


class CreateUser(CreateView):

    
    model = User
    template_name = 'accounts/create.html'
    form_class = CreationUserForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        messages.success(
            self.request,'Cadastro realizado com sucesso! Faça seu login.'
        )
                
        return super().form_valid(form)


class UpdateUser(LoginRequiredMixin, UpdateView):


    model = User
    login_url = reverse_lazy('accounts:login_user')
    template_name = 'accounts/create.html'
    form_class = ChangeUserForm
    success_url = reverse_lazy('accounts:home_user')

    def get_object(self):
        return self.request.user
    
    def form_valid(self, form):
        messages.success(self.request, 
            f'{self.get_object().name} alterado com sucesso!'
        )
        return super().form_valid(form)


class DeleteUser(LoginRequiredMixin, DeleteView):


    model = User
    login_url = reverse_lazy('accounts:login_user')
    template_name = 'accounts/delete.html'
    success_url = reverse_lazy('home')

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        
        messages.success(self.request,
            'Perfil apagado com sucesso!'
        )
        return super().get_success_url()


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    
    
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/password_reset_email.html'
    subject_template_name = 'accounts/password_reset_subject'
    success_message = "Enviamos um e-mail com instruções para definir sua senha, " \
                       "se existir uma conta com o e-mail que você digitou. Você deve recebê-lo em breve." \
                       "Se você não receber um e-mail, " \
                       "certifique-se de que inseriu o endereço com o qual se registrou e verifique sua pasta de spam."
    success_url = reverse_lazy('home')

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block container %}
    <h2>Mudar senha</h2>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
            <div class="form-group">
            {{form|crispy}}
        </div>
        <button type="submit" class="save btn btn-success ">Salvar</button>
    </form>
{% endblock %}

templates/accounts/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block container %}
<h2>Cadastra e alterações de usuário</h2>
    <form method="POST" class="table" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <div class="d-flex justify-content-end">
            <a class="btn-lg btn-default text-danger" href="javascript:history.back()">Cancelar</a>
            <button type="submit" class="save btn-lg btn-success">Salvar</button>
        </div>
    </form>
{% endblock %}

templates/accounts/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block container %}

{% if user.is_authenticated or user.is_superuser %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="page-header">
                <h1>Apagar</h1>
            </div>
            <form action="" method="POST">
                <p><strong>{{ object }}</strong> Você realmente deseja apagar sua conta com todos os seus dados?</p>
                <p class="text-danger">OBS: Ao apagar sua conta a sua lista de tarefas será eliminada do sistema de uma vez por todas e sendo impossível recuperá-la novamente.</p>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Excluir</button>
                
                <a href="javascript:history.back()"> 
                    <button type="button" class="btn btn-outline-danger">Cancelar</button>
                </a>
            </form>
        </div>
    </div>
{% else %}
    <div class="alert alert-warning">
        Você não tem permissão para acessar essa página, faça <a href="/accounts/login/">login aqui.</a>
    </div>
{% endif %}

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block container %} 
<div class="row justify-content-center">
  <div class="col-md-8 col-md-offset-2"> 
    <div class="page-header"> 
        <h1 class="font-weight-light my-4 text-center">Login</h1>
        {% for error in form.non_field_errors %}
                  <div class='alert alert-danger'>
                      {{ error }}
                  </div>
        {% endfor %}
    </div>  
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Usuário:</label>
            <input name="username" type="text" class="form-control" required>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Senha:</label>
            <input name="password" type="password" class="form-control" required>
        </div>
        <div class="form-row">
            <div class="col-md-10 offset-md-1">
              <div class="form-group mt-0 mb-1">
                  <button type="submit" class="col-md-12 btn btn-success">Entrar
                  </button>
              </div>
           </div>
         </div>
    </form>
</div>
<div class="text-center">
    <div class="small">
        <a href="/accounts/password-reset/">
            <h6 class="text-danger">Esqueceu ou deseja redefinir sua senha?</h6>
        </a>
    </div>
</div>            
{% endblock container %}

templates/accounts/password_reset.html
{% extends "base.html" %}
{% block container %}
<div class="card-body">
<div class="row justify-content-center">
  <div class="col-md-8 col-md-offset-2"> 
    <div class="page-header">
      <div class="card-body">
        <h5>Insira seu email válido abaixo para o envio de um link de redefinição de sua senha.</h5>
      </div> 
        {% for error in form.non_field_errors %}
                  <div class='alert alert-danger'>
                      {{ error }}
                  </div>
        {% endfor %}
    </div>  
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">E-mail:</label>
            <input name="email" type="email" class="form-control" required>
        </div>
        <div class="form-row">
            <div class="col-md-10 offset-md-1">
              <div class="form-group mt-0 mb-1">
                  <button type="submit" class="col-md-12 btn btn-success">Enviar
                  </button>
              </div>
           </div>
         </div>
    </form>
    <div class="col-md-10 offset-md-1">
      <div class="form-group mt-0 mb-1">
        <a class="text-dark" href="javascript:history.back()">Voltar</a>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block container %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Sua senha foi edefinida. Você pode ir em frente e <a href="/accounts/login/">login aqui.</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock container %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block container %}

    {% if validlink %}
    <h2>Redefinir senha</h2>
        <form method="POST" class="table" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="form-group">
                {{form|crispy}}
            </div>
            <button type="submit" class="save btn btn-success ">Salvar</button>
        </form>
    {% else %}
        <div class="alert alert-warning">
            O link de redefinição de senha está inválido, possivelmente porque já foi usado.
            Solicite uma nova redefinição de senha.
        </div>
    {% endif %}
{% endblock %}

templates/accounts/password_reset_email.html
{% autoescape off %}
Para iniciar o processo de redefinição de senha para seu {{ user.email }} Django Registration/Login App Account,
clique no link abaixo:

  {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

  Se clicar no link acima não funcionar, copie e cole a URL em uma nova janela do navegador.

{% endautoescape %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% block container %} 
<div class="card">
  <div class="card-header container d-flex justify-content-between">
    Dados cadastrais
    <div>
      <div class="form-group mt-0 mb-1">
        <a class="btn btn-outline-danger" href="javascript:history.back()">Voltar</a>
      </div>
    </div>
  </div>
  <div class="card-body">
    <h5 class="card-title"><b>{{ user.name }}</b></h5>
    <p class="card-text"><b>Username: </b>{{ user.username }}</p>
    <p class="card-text"><b>E-mail: </b>{{ user.email }}</p>
    <p class="card-text"><b>Status: </b>
      {% if user.is_active %}
        Ativo
      {% else %}
        Inativo
      {% endif %}
    </p>
  
    <div class="container pt-3">
      <div class="row g-2">
        <div class="col-12 col-md-2 order-2 order-md-1">
            <a class="btn btn-primary" href="/accounts/update/" class="card-link">Alterar dados</a>
        </div>
        <div class="col-12 col-md-2 order-1 order-md-2">
            <a class="btn btn-primary" href="/accounts/change-password/">Mudar a senha</a>
        </div>
        <div class="col-12 col-md-2 order-3">
            <a class="btn btn-danger" href="/accounts/delete/" class="card-link">Excluir conta</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}